#!/bin/bash

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

PLUGIN_DIR="./plugins"

ITEM_DIR="./items/"

source "./userconfig.sh"
source "./colors.sh"
source "./plugins/icon_map.sh"

bar=(
  height=30
  color=$BASE
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=4
  margin=8
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# sketchybar 	--add event 				hide_stats   					                                      \
#            	--add event 				show_stats 					                                        \
#            	--add event 				toggle_stats 					                                      \
#                                                            										              \
#            	--add item         	animator right                									            \
#            	--set animator     	drawing=off                  									              \
#                               	updates=on                   									              \
#                               	script="$HOME/.config/sketchybar/plugins/toggle_stats.sh"   \
#            	--subscribe        	animator hide_stats show_stats toggle_stats
#
#

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item animator right \
           --add event hide_stats \
           --add event show_stats \
           --add event toggle_stats \
           --set animator drawing=off updates=on script="$HOME/.config/sketchybar/plugins/toggle_stats.sh" \
           --subscribe animator hide_stats show_stats toggle_stats \
           --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

source "./items/stats.sh"
# source "./items/keyboard.sh"
source "$ITEM_DIR/volume.sh"

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
