# Doesn't need to be sourced in zshrc because is always sourced by zshrc first when starting new shell

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Flyctl paths
export FLYCTL_INSTALL="$HOME/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

# Airplane paths
export AIRPLANE_INSTALL="$HOME/.airplane"
export PATH="$AIRPLANE_INSTALL/bin:$PATH"

# nvm paths
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# deno paths
export DENO_INSTALL="/home/gmkonan/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
