# Zplug 
source ~/.zplug/init.zsh

#zplug "mafredri/zsh-async", from:github
#zplug "marlonrichert/zsh-autocomplete", from:github
zplug "plugins/git",   from:oh-my-zsh, defer:1
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zdharma-continuum/fast-syntax-highlighting", defer:2
zplug "so-fancy/diff-so-fancy"
zplug "sharkdp/bat"
zplug "nvbn/thefuck"

# Load theme file
zplug "spaceship-prompt/spaceship-prompt", use:spaceship.zsh, from:github, as:theme

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

CONFIGS_DIR=$(dirname $(readlink ~/.zshenv))

SPACESHIP_PROMPT_ORDER=(
  #user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  docker
  docker_compose
  exec_time     # Execution time
  line_sep      # Line break
  #vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_DIR_COLOR="cyan"

if [ -f "$HOME"/.aliases ]; then
  source "$HOME"/.aliases
fi

if [ -f "$HOME"/.secrets ]; then
  source "$HOME"/.secrets
fi