#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="./plugins"

ITEM_DIR="./items/"

# source $CONFIG_DIR/colors.sh
source "./userconfig.sh"
source "./colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see: https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=40
  color=$BASE
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=4
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="$NERD_FONT:Bold:17.0"
  label.font="$NERD_FONT:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# sketchybar 	--add event 				hide_stats   					                                      \
#            	--add event 				show_stats 					                                        \
#            	--add event 				toggle_stats 					                                      \
#                                                            										              \
#            	--add item         	animator right                									            \
#            	--set animator     	drawing=off                  									              \
#                               	updates=on                   									              \
#                               	script="$HOME/.config/sketchybar/plugins/toggle_stats.sh"   \
#            	--subscribe        	animator hide_stats show_stats toggle_stats
#
#

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item animator right \
           --add event hide_stats \
           --add event show_stats \
           --add event toggle_stats \
           --set animator drawing=off updates=on script="$HOME/.config/sketchybar/plugins/toggle_stats.sh" \
           --subscribe animator hide_stats show_stats toggle_stats \
           --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

source "./items/stats.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
